#!/bin/bash

code --install-extension aaron-bond.better-comments --force
code --install-extension akopachov.change-case-ex --force
code --install-extension angular.ng-template --force
code --install-extension atommaterial.a-file-icon-vscode --force
code --install-extension bmewburn.vscode-intelephense-client --force
code --install-extension bradlc.vscode-tailwindcss --force
code --install-extension dbaeumer.vscode-eslint --force
code --install-extension devsense.composer-php-vscode --force
code --install-extension echoapi.echoapi-for-vscode --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension eugenejeon.codesnap-plus-fix --force
code --install-extension firefox-devtools.vscode-firefox-debug --force
code --install-extension firsttris.vscode-jest-runner --force
code --install-extension formulahendry.auto-rename-tag --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension graphql.vscode-graphql-syntax --force
code --install-extension johnbillion.vscode-wordpress-hooks --force
code --install-extension k--kato.intellij-idea-keybindings --force
code --install-extension laravel.vscode-laravel --force
code --install-extension mansoorkhan96.php-cs-fixer --force
code --install-extension matthiashunt.wordpress-syntax-highlighter --force
code --install-extension mintlify.document --force
code --install-extension mongodb.mongodb-vscode --force
code --install-extension ms-playwright.playwright --force
code --install-extension ms-python.black-formatter --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.isort --force
code --install-extension ms-python.mypy-type-checker --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-vscode.vscode-typescript-next --force
code --install-extension oasin.theme-dark-plus-darcula --force
code --install-extension orta.vscode-jest --force
code --install-extension quicktype.quicktype --force
code --install-extension redhat.vscode-xml --force
code --install-extension redhat.vscode-yaml --force
code --install-extension sanderverschoor.vscode-symfony-ux-twig-component --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension unifiedjs.vscode-mdx --force
code --install-extension usernamehw.errorlens --force
code --install-extension valeryanm.vscode-phpsab --force
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
code --install-extension vitest.explorer --force
code --install-extension vue.volar --force
code --install-extension xdebug.php-debug --force
